source 'https://rubygems.org'

gem 'rails', '3.2.13'

group :test, :development do 
	gem 'rspec-rails'
	gem 'factory_girl_rails'
end

group :asset do 
	gem 'uglifier'
end

gem 'sqlite3'

gem 'privacy_setting', :path => '../'